# Build initial image
ARG IMAGE_NODE_ALPINE_VERSION=node:16.13.2-alpine3.15

FROM ${IMAGE_NODE_ALPINE_VERSION} as builder

LABEL maintainer="Renato Gomes <renatogomessilverio@gmail.com>"

RUN /bin/sh -c "apk add --no-cache bash" && \
    apk update && apk add curl wget git vim htop python3 py3-pip busybox-extras figlet && \
    npm install -g @angular/cli@13

SHELL ["/bin/bash", "-c"]

WORKDIR /APP
